import React from "react";
import { Link } from "react-router-dom";
import workwithus from ".//../";

export default function Shipping() {
  return (
    <>
      <div className=" my-10 lg:mx-20   font-mono   ">
        <div className="lg:block hidden">
          <Link to={"/"} className="hover:underline py-10 font-bold">
            Home &nbsp;
          </Link>
          <span>&#62;</span>

          <span className="px-5">Shipping, Returns & Cancellations</span>
        </div>

        <div className="m-10 space-y-5 ">
          <h2 className="my-2 text-2xl font-semibold">Terms & Conditions</h2>
          <p className="xm:text-xs lg:text-sm">
            This Policy is projected to all personal information and sensitive
            personal data or information that is given by or obtained from any
            person who visits or uses or accesses the website ("User"). We
            reserve the right to modify or review the details of this Policy
            without prior notice and the revised Policy will be in effect from
            the day of uploading. Therefore, Users are requested to periodically
            visit the website and review the policy.
          </p>
          <p className="xm:text-xs lg:text-sm">
            <span className="text-lg text-blue-800 font-semibold">
              Rule 1 : &nbsp;
            </span>
            A User may be required to give away some Personal Information,
            including Sensitive Personal Information while browsing through the
            website or for availing services at the website.
          </p>
          <p className="xm:text-xs lg:text-sm">
            <span className="text-lg text-blue-800 font-semibold">
              Rule 2 : &nbsp;
            </span>
            Personal Information disclosed to Us by a User will be used by Us
            for one or more of the following purposes: (a) to help Us in
            creating content that is relevant to the User; (b) to collect a
            database of all the Personal Information collected from User
          </p>
          <p className="xm:text-xs lg:text-sm">
            <span className="text-lg text-blue-800 font-semibold">
              Rule 3 : &nbsp;
            </span>
            When a User visits the website, one or more cookies shall be sent to
            a computer or the device being used by the User to visit the
            websites. Cookies are used upscale the quality of the services
            provided by Us, including for keeping User preferences...
          </p>
        </div>

        <div className="m-10 space-y-5 ">
          <h2 className="my-2 text-2xl font-semibold text-center">
            Shipping, Returns & Cancellation
          </h2>
          <p className="xm:text-xs lg:text-sm">
            We are always excited to ship the books that you order!
          </p>
          <p className="xm:text-xs lg:text-sm">
            We make every possible effort to deliver your books at the earliest
            so that you can kick start your exam preparation journey with Disha
            as soon as possible. All kinds of assistance are available from our
            end via WhatsApp, Call and Email during and after the processing of
            your order. We request you to provide us your complete and accurate
            information including a functional mobile number to avoid
            unnecessary delays and issues.
          </p>
          <p className="xm:text-xs lg:text-sm">
            We use the safest payment gateways for online payments. Please note
            that we NEVER call or text our customers to ask for any OTPs
            generated by their banks.
          </p>
          <p className="xm:text-xs lg:text-sm">
            Kindly go through our Policies on Shipping, Dispatch, Cancellation,
            Return and Refund of orders.
          </p>
        </div>

        <div className="m-10 space-y-5  ">
          <h2 className="my-2 text-lg font-semibold t">Order and Dispatch</h2>

          <ul className="space-y-5 list-disc">
            <li className="xm:text-xs lg:text-sm">
              We accept both kinds of orders: &nbsp;
              <span className="xm:text-xs lg:text-lg text-blue-800 font-semibold">
                1. COD or Cash On Delivery orders,&nbsp;
              </span>
              and : &nbsp;
              <span className="xm:text-xs lg:text-lg text-blue-800 font-semibold">
                2. Pre-paid orders &nbsp;
              </span>
              at the time of checkout through different digital payment modes.
            </li>
            <li className="xm:text-xs lg:text-sm">
              No delivery fee is charged on Pre-paid orders of INR 125/- and
              above.
            </li>
            <li className="xm:text-xs lg:text-sm">
              Orders once placed with us cannot be modified or clubbed with any
              other order.
            </li>
            <li className="xm:text-xs lg:text-sm">
              For all COD (Cash On Delivery) orders, an extra delivery fee of
              Rs. 90/- is applicable on every order.
            </li>
            <li className="xm:text-xs lg:text-sm">
              COD is available only on a minimum cart value of INR 175/- and
              maximum cart value of INR 1000/-
            </li>
            <li className="xm:text-xs lg:text-sm">
              If you place an order via COD option, our executive will call you
              to confirm your order. Please be available on call on the given
              number that you provide us with your delivery information.
            </li>
            <li className="xm:text-xs lg:text-sm">
              After dispatch, the customer has to accept the product and he or
              she cannot refuse/return the product.
            </li>
            <li className="xm:text-xs lg:text-sm">
              We share with you the shipping information including a Tracking
              ID, and other relevant details on WhatsApp and/or Email.
            </li>
            <li className="xm:text-xs lg:text-sm">
              You will receive updates on order pick up, shipment, expected date
              of delivery, etc., on your WhatsApp number.
            </li>
            <li className="xm:text-xs lg:text-sm">
              You can track your order using the tracking number provided in
              your order confirmation email by visiting our delivery partner’s
              website. It may take up to 12-24 hours to update your tracking
              number on our website.
            </li>
            <li className="xm:text-xs lg:text-sm">
              We ship all over India in business days, i.e., Monday to Saturday,
              excluding national holidays and major festivals.
            </li>
            <li className="xm:text-xs lg:text-sm">
              We work with shipping partners all over the country to get your
              books delivered at your doorstep. Although the vast majority of
              our customers will get their orders within 7-10 business days,
              actual timeframes may vary from region to region. For example, if
              your delivery location is in Jammu & Kashmir and the North Eastern
              states, it might take longer.
            </li>
            <li className="xm:text-xs lg:text-sm">
              We do not accept international orders. However, you may make an
              enquiry about the same on our customer care number/email.
            </li>
            <li className="xm:text-xs lg:text-sm">
              We, at Disha Publication, have hired the best courier services to
              get your books delivered quickly. However, sometimes, due to
              unavoidable circumstances, there may be a delay.
            </li>
          </ul>
        </div>

        <div className="m-10 space-y-5  ">
          <h2 className="my-2 text-lg font-semibold t">
            Return and Refund Policy
          </h2>

          <ul className="space-y-5 list-disc">
            <li className="xm:text-xs lg:text-sm">
              All books purchased from Disha Publication are non-returnable,
              unless stated otherwise.
            </li>
            <li className="xm:text-xs lg:text-sm">
              If the book that you receive is damaged, send us a photo or video
              of the same on our customer care WhatsApp number or email id.
              After proper examination by the team, we will re-send you the same
              book in good condition.
            </li>
            <li className="xm:text-xs lg:text-sm">
              If you receive a wrong book different from the one you ordered,
              please let us know through our customer care. We will pick up the
              wrong book and ship you the correctbook immediately after
              receiving the wrong one. If you are in a hurry to get the book
              before we complete the picking up and re-dispatch process, you can
              place a fresh order for the same book through this website. We
              will refund the money charged for the wrong book after receiving
              it. However, refund is applicable only if your fresh order exactly
              matches your previous order (in terms of book titles) for which
              the replacement process was initiated.
            </li>
          </ul>
        </div>

        <div className="m-10 space-y-5  ">
          <h2 className="my-2 text-lg font-semibold t">Cancellation Policy</h2>

          <ul className="space-y-5 list-disc">
            <li className="xm:text-xs lg:text-sm">
              You may cancel your order within 24 hours of placing it. A
              cancellation fee of INR 99/- will be deducted and the rest will be
              refunded in case of Pre-paid orders
            </li>
            <li className="xm:text-xs lg:text-sm">
              Your order is not eligible for cancellation and refund if it
              exceeds the window of 24 hours. This is because we start
              processing your order within a day of receiving it.
            </li>
            <li className="xm:text-xs lg:text-sm">
              In special cases, we might consider cancellation and refund after
              24 hours. In such cases, pleasetalk to our customer care executive
              to discuss what can be done about your order.
            </li>
          </ul>
        </div>
        <p className="xm:text-xs lg:text-sm">
          If you still have queries or doubts, please check out our FAQ section.
          We sincerely hope that you have a happy shopping experience with Disha
          Publication!
        </p>
      </div>
    </>
  );
}
